<?php

use App\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::create([
            'name'      =>  'Root',
            'surname'      =>  'Root',
            'razon'      =>  'Razón Social',
            'address'      =>  'direccion',
            'city'      =>  'ciudad',
            'pc'      =>  '11600',
            'province'      =>  'Cádiz',
            'phone'      =>  '956848383',
            'NIF'      =>  '31848383',
            'email'     =>  'root@example.com',
            'root'     =>  true,
            'password'  =>  bcrypt('root')
        ]);

        User::create([
            'name'      =>  'Tecnico',
            'surname'      =>  'Apellidos',
            'razon'      =>  'Razón Social',
            'address'      =>  'direccion',
            'city'      =>  'ciudad',
            'pc'      =>  '11600',
            'province'      =>  'Cádiz',
            'phone'      =>  '956848384',
            'NIF'      =>  '31848384',
            'email'     =>  'tecnico@example.com',
            'tecnico'     =>  true,
            'password'  =>  bcrypt('root')
        ]);

        User::create([
            'name'      =>  'Administrativo',
            'surname'      =>  'Administrativo',
            'razon'      =>  'Razón Social',
            'address'      =>  'direccion',
            'city'      =>  'ciudad',
            'pc'      =>  '11600',
            'province'      =>  'Cádiz',
            'phone'      =>  '956848385',
            'NIF'      =>  '31848385',
            'email'     =>  'administrativo@example.com',
            'admin'     =>  true,
            'password'  =>  bcrypt('root')
        ]);

        User::create([
            'name'      =>  'Comercial',
            'surname'      =>  'Comercial',
            'razon'      =>  'Razón Social',
            'address'      =>  'direccion',
            'city'      =>  'ciudad',
            'pc'      =>  '11600',
            'province'      =>  'Cádiz',
            'phone'      =>  '956848385',
            'NIF'      =>  '31848385',
            'email'     =>  'comercial@example.com',
            'comercial' =>  true,
            'password'  =>  bcrypt('root')
        ]);

        User::create([
            'name' =>  'Cliente', 'surname' =>  'Normal', 'razon' =>  'Razón Social', 'address' => 'direccion',
            'city'      =>  'ciudad', 'pc' =>  '11600', 'province' =>  'Cádiz', 'phone'      =>  '956848385',
            'NIF'      =>  '31848385', 'email'     =>  'cliente@example.com', 'password'  =>  bcrypt('root')
        ]);

        User::create([ 'NIF'      =>  '15439717R',  'name'      =>  'ABRAHAN',  'surname'      =>  'ROMANO PEREZ',  'razon'      =>  'ABRAHAN ROMANO PEREZ',    'address'      =>  'C/ CALLEJON DE LA HORCA',   'pc'      =>  '11648',  'city'      =>  'ESPERA',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000079',  'email'      =>  'ABRAHANROMANOPEREZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72185499',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AGROALIMENTARIA EL BUCARITO SL',  'address'      =>  'DE LA LUNA',    'pc'      =>  '11520',  'city'      =>  'ROTA', 'province'      =>  'Cádiz',    'phone'      =>  '607700279',   'codigo'      =>  '4300030000172',  'email'      =>  'AGROALIMENTARIAELBUCARITO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11917671',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AGROGANADERA MONTESIERA, SL', 'address'      =>  'AV JUAN CARLOS 1ºROTON',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000081',  'email'      =>  'AGROGANADERAMONTESIERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11332400',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ALBAÑ Y CONST CEYVE, SL', 'address'      =>  'AV LIBERTAD',   'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000075',  'email'      =>  'ALBAÑYCONSTCEYVE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72283328',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ALCOSUR HIGINIO, SL', 'address'      =>  'CR MOLINO VIEJO',   'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '618168365',   'codigo'      =>  '4300030100071',  'email'      =>  'ALCOSURHIGINIO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72101660',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ALVA GESTION',    'address'      =>  'AVD CAÑADA HONDA',  'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '956444360',   'codigo'      =>  '4300030000048',  'email'      =>  'ALVAGESTION@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B18239459',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ANFRASA', 'address'      =>  'C/ BEETHOVEN',  'pc'      =>  '18006',  'city'      =>  'Granada',  'province'      =>  'Granada',  'phone'      =>  '958125852',   'codigo'      =>  '4300030000164',  'email'      =>  'ANFRASA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72356298',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ANGEL VIDAL CONSTRUCCIONES Y REVESTIMIENTOS, SL', 'address'      =>  'DIOS AMON', 'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000106',  'email'      =>  'ANGELVIDALCONSTRUCCIONESYREVESTIMIENTOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A11612132',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ANTONIO CANTALEJO SA',    'address'      =>  'CTRA CORTES KM',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000171',  'email'      =>  'ANTONIOCANTALEJO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31585674G',  'name'      =>  'ANTONIO',  'surname'      =>  'JAEN ORIHUELA', 'razon'      =>  'ANTONIO JAEN ORIHUELA',   'address'      =>  'PG IND PORTAL C SUDAFRICA', 'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000047',  'email'      =>  'ANTONIOJAENORIHUELA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75864092H',  'name'      =>  'ANTONIO',  'surname'      =>  'RODRIGUEZ JIMENEZ', 'razon'      =>  'ANTONIO RODRIGUEZ JIMENEZ',   'address'      =>  'C/ SAN SEBASTIAN',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '687283048',   'codigo'      =>  '4300010000114',  'email'      =>  'ANTONIORODRIGUEZJIMENEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72321946',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'APLIVEN MCV SL',  'address'      =>  'AVDA ATALAYA',  'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000194',  'email'      =>  'APLIVENMCV@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11900362',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AQUA DECOR',  'address'      =>  'AV DE ARCOS ED ATRIUM LOCAL BA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '645946400',   'codigo'      =>  '4301000000203',  'email'      =>  'AQUADECOR@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11934122',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARCOBROC,SL', 'address'      =>  'C/ MALVA',  'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4303000000163',  'email'      =>  'ARCOBROC@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11877628',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARCOSCONS S.L.',  'address'      =>  'C/ BENITO ZAMBRANO',    'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000212',  'email'      =>  'ARCOSCONS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11859188',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARIAN PATRIMONIO, SL',    'address'      =>  'PLZ MADRE DE DIOS', 'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000173',  'email'      =>  'ARIANPATRIMONIO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11382785',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARIDOS LA HERRADURA, SL', 'address'      =>  'LG LA BARCA DE VEJER',  'pc'      =>  '11150',  'city'      =>  'VEJER DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '620860284',   'codigo'      =>  '4300030100015',  'email'      =>  'aridos@aridoslaherradura.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11676434',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARIDOS Y MAT. CER RIVE, SL',  'address'      =>  'ALCALDE CANTOS ROPERO', 'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956140345',   'codigo'      =>  '4300010000134',  'email'      =>  'caleriarive@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A11626108',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ARTICUERO, SA',   'address'      =>  'PI EL CHAPARRAL NAVE',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000186',  'email'      =>  'ARTICUERO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72213457',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ATLANTERRA PROYECTOS SL', 'address'      =>  'CABO DE PLATA', 'pc'      =>  '11393',  'city'      =>  'ZAHARA DE LOS ATUNES', 'province'      =>  'Cádiz',    'phone'      =>  '956457167',   'codigo'      =>  '4300010000045',  'email'      =>  'avt@atlanterra.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72246424',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AZULEJOS HNOS GARCIA 2014, SL',   'address'      =>  'PG IND TRES CAMINOS MANZ 9 PAR',    'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '956590162',   'codigo'      =>  '4300030000057',  'email'      =>  'AZULEJOSHNOSGARCIA2014@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11827367',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AZULEJOS LA FUENTEZUELA, SL', 'address'      =>  'PL PARQUE EMPRES FUENTEZUELA',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '956730980',   'codigo'      =>  '4300010000110',  'email'      =>  'AZULEJOSLAFUENTEZUELA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11235330',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'AZULEJOS PUERTO SUR, SL', 'address'      =>  'C/ PEDRO SANZ', 'pc'      =>  '11659',  'city'      =>  'PUERTO SERRANO',   'province'      =>  'Cádiz',    'phone'      =>  '956136340',   'codigo'      =>  '4300010000008',  'email'      =>  'azulejospuertosur@hotmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72199615',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BAHIA GADIR INVERSIONES, SL', 'address'      =>  'C/ ALBAR',  'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000014',  'email'      =>  'BAHIAGADIRINVERSIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11901105',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BARVAL CONSTRUCCIONES,SL',    'address'      =>  'C/EDGAR NEVILLE',   'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000136',  'email'      =>  'BARVALCONSTRUCCIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90078542',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BEJAYSIN,SL', 'address'      =>  'C/ MOLINOS',    'pc'      =>  '41740',  'city'      =>  'LEBRIJA',  'province'      =>  'Sevilla',  'phone'      =>  '955979696',   'codigo'      =>  '4300010000093',  'email'      =>  'BEJAYSIN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31609062R',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BENITO CORDERO DIAZ ',    'address'      =>  'C/ GIBALBIN',   'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'SEVILLLA', 'phone'      =>  '',    'codigo'      =>  '4301000000026',  'email'      =>  'BENITOCORDERODIAZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90186867',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BIOAGRO TECH, SL',    'address'      =>  'VIVERO DE INNV PI LA SERNA',    'pc'      =>  '31500',  'city'      =>  'TUDELA',   'province'      =>  'NAVARRA',  'phone'      =>  '',    'codigo'      =>  '4300010000185',  'email'      =>  'BIOAGROTECH@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A11606779',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'BODEGAS WILIAM & HUMBERT',    'address'      =>  'CTRA N-IV MADRID-Cádiz KM 641,',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000050',  'email'      =>  'BODEGASWILIAM&HUMBERT@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11719937',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CALERIA CABRAL, SL',  'address'      =>  'AV BLAS INFANTE',   'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956401116',   'codigo'      =>  '4300030100052',  'email'      =>  'info@paraconstruir.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72205354',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CALERIA GARCIA, SL',  'address'      =>  'C/ NTR SÑR DEL PILAR',  'pc'      =>  '11510',  'city'      =>  'PUERTO REAL',  'province'      =>  'Cádiz',    'phone'      =>  '956833541',   'codigo'      =>  '4300030100077',  'email'      =>  'CALERIAGARCIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31702654Y',  'name'      =>  'CARLOS',   'surname'      =>  'CAMACHO PANAL', 'razon'      =>  'CARLOS CAMACHO PANAL',    'address'      =>  'AVDA HERRERA ODIA', 'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '625274707',   'codigo'      =>  '4301000000205',  'email'      =>  'CARLOSCAMACHOPANAL@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31402841K',  'name'      =>  'CAYETANO', 'surname'      =>  'GUERRA PRIAM',  'razon'      =>  'CAYETANO GUERRA PRIAM',   'address'      =>  'SAN JUAN BOSCO',    'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '699903643',   'codigo'      =>  '4300030000175',  'email'      =>  'construccionesprian@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41099938',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CID MAYO, SL',    'address'      =>  'AV UTRERA', 'pc'      =>  '41720',  'city'      =>  'LOS PALACIOS', 'province'      =>  'Sevilla',  'phone'      =>  '955811351',   'codigo'      =>  '4300010000085',  'email'      =>  'CIDMAYO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11734654',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'COBOS Y ROMAN, SL',   'address'      =>  'C/ MORENOS',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '658982272',   'codigo'      =>  '4300010000178',  'email'      =>  'COBOSYROMAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11727518',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'COHEROGRAN, SL',  'address'      =>  'C/ SAN FRANCISCO',  'pc'      =>  '11580',  'city'      =>  'SAN JOSE DEL VALLE',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000141',  'email'      =>  'COHEROGRAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72266158',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'COMERCIAL FONTANERIA Y FERRET,',  'address'      =>  'AV MAYORAZGO',  'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000072',  'email'      =>  'COMERCIALFONTANERIAYFERRET@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A43039288',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'COMPAÑIA ESPAÑOLA DE AISLAMIENTO, SA',    'address'      =>  'SAN JOSE ARTESANO', 'pc'      =>  '28100',  'city'      =>  'ALCOBENDAS',   'province'      =>  'MADRID',   'phone'      =>  '',    'codigo'      =>  '4300030000182',  'email'      =>  'COMPAÑIAESPAÑOLADEAISLAMIENTO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11946449',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONCERAN OBRAS SL',   'address'      =>  'SALINERAS', 'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000144',  'email'      =>  'CONCERANOBRAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72205495',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONFORT GRES SL', 'address'      =>  'PZ REYES CATOLICOS',    'pc'      =>  '11160',  'city'      =>  'BARBATE ', 'province'      =>  'Cádiz',    'phone'      =>  '661711691',   'codigo'      =>  '4300030100003',  'email'      =>  'comercial.confortgres@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11692878',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONS JM GONZALEZ RODRIGUEZ,SL',   'address'      =>  'C/ REAL',   'pc'      =>  '11639',  'city'      =>  'ALGAR',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000094',  'email'      =>  'antonio@construccionesgonzalezrodriguez.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11468576',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONST DESTAM BENALUP, SL',    'address'      =>  'C/ JORNALERO NV 40',    'pc'      =>  '11190',  'city'      =>  'BENALUP-CASAS VIEJAS', 'province'      =>  'Cádiz',    'phone'      =>  '609347410',   'codigo'      =>  '4300030100021',  'email'      =>  'destamp1@hotmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11356722',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONST GUERRERO BARBERA, SL',  'address'      =>  'C/ ALBAÑILES',  'pc'      =>  '11190',  'city'      =>  'BENALUP-CASAS VIEJAS', 'province'      =>  'Cádiz',    'phone'      =>  '956417855',   'codigo'      =>  '4300001000171',  'email'      =>  'CONSTGUERREROBARBERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11689528',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONST MATEOS BELTRAN, SL',    'address'      =>  'AVD FELIX RODRIGUEZ DE LA FUEN',    'pc'      =>  '11660',  'city'      =>  'PRADO DEL REY',    'province'      =>  'Cádiz',    'phone'      =>  '956723664',   'codigo'      =>  '4300010000172',  'email'      =>  'CONSTMATEOSBELTRAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11333184',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES BERMUDEZ CALDERON, SL',    'address'      =>  'CR DEL MUELLE', 'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '615586931',   'codigo'      =>  '4300030100032',  'email'      =>  'bermudezcalderonsl@yahoo.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11328085',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES CAÑINO SL',    'address'      =>  'LA ROSA',   'pc'      =>  '11670',  'city'      =>  'EL BOSQUE',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000130',  'email'      =>  'manolo_trujillano@hotmail.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11828910',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES DIROD, SL',    'address'      =>  'C/ RAFAEL ALBERTI', 'pc'      =>  '11580',  'city'      =>  'SAN JOSE DEL VALLE',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000074',  'email'      =>  'CONSTRUCCIONESDIROD@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11536737',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES FERNANDEZ CHIPIONA, SL',   'address'      =>  'C/ CORRAL HONDO',   'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '607978929',   'codigo'      =>  '4300010000164',  'email'      =>  'CONSTRUCCIONESFERNANDEZCHIPIONA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11617594',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES FRANCISCO MANZANO, SL',    'address'      =>  'CR JEREZ ARCOS KM 26',  'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000113',  'email'      =>  'CONSTRUCCIONESFRANCISCOMANZANO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11834371',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES JAIME ROMAN, SL',  'address'      =>  'C/ ENCRUCIJADA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000135',  'email'      =>  'CONSTRUCCIONESJAIMEROMAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11936663',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES JCM ARCOS SL', 'address'      =>  'C/PINTOR MADRAZO',  'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000196',  'email'      =>  'CONSTRUCCIONESJCMARCOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11721453',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES JUAN GARCIA CONTRERAS, SL',    'address'      =>  'SAN JOSE, C/ PALOMA',   'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000200',  'email'      =>  'CONSTRUCCIONESJUANGARCIACONTRERAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90401928',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES JUGUEVI 2018 SL',  'address'      =>  'PALOMA',    'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000126',  'email'      =>  'CONSTRUCCIONESJUGUEVI2018@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41632415',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES MAXIMO CRUZ SL',   'address'      =>  'C/ CUESTA PORTILLO',    'pc'      =>  '41530',  'city'      =>  'MORON DE LA FRONTERA', 'province'      =>  'Sevilla',  'phone'      =>  '687486146',   'codigo'      =>  '4300001000213',  'email'      =>  'CONSTRUCCIONESMAXIMOCRUZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B43004852',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONSTRUCCIONES OTERO, SL',    'address'      =>  'C/ACEQUIA PQ CORTIJO COND', 'pc'      =>  '18008',  'city'      =>  'Granada',  'province'      =>  'Granada',  'phone'      =>  '',    'codigo'      =>  '4300010000187',  'email'      =>  'CONSTRUCCIONESOTERO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91214346',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'CONTRATAS GUTIERREZ, SL', 'address'      =>  'RIO BLANCO',    'pc'      =>  '41400',  'city'      =>  'ECIJA',    'province'      =>  'Sevilla',  'phone'      =>  '955901141',   'codigo'      =>  '4300030000179',  'email'      =>  'gestion@contratasgutierrez.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31709145B',  'name'      =>  'DARIO ',   'surname'      =>  'SANTOS GARCIA', 'razon'      =>  'DARIO SANTOS GARCIA', 'address'      =>  'BD SAN JOSE OBRERO PLA',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000022',  'email'      =>  'DARIOSANTOSGARCIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91974816',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'DESARROLLO INT SOST DE CONS , SL',    'address'      =>  'C/ ALBACETE',   'pc'      =>  '41730',  'city'      =>  'LAS CABEZAS DE SAN JUAN',  'province'      =>  'Sevilla',  'phone'      =>  '616444372',   'codigo'      =>  '4300010000007',  'email'      =>  'dintec@hotmail.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72265986',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'DESARROLLO SUB CONSTRUCCION SL',  'address'      =>  'LA FUENTEZUELA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '622325361',   'codigo'      =>  '4300010000044',  'email'      =>  'dsconstruccionsl@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31530585T',  'name'      =>  'DIEGO',    'surname'      =>  'ROMERO RUIZ',   'razon'      =>  'DIEGO ROMERO RUIZ',   'address'      =>  'AVD EL CASERON',    'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '605100258',   'codigo'      =>  '4300030100028',  'email'      =>  'kaena2009@hotmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31611725P',  'name'      =>  'DIEGO',    'surname'      =>  'VELAZQUEZ MENENDEZ',    'razon'      =>  'DIEGO VELAZQUEZ MENENDEZ',    'address'      =>  'C/ GUERRERO SANCHEZ',   'pc'      =>  '11660',  'city'      =>  'PRADO DEL REY',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000158',  'email'      =>  'DIEGOVELAZQUEZMENENDEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72238496',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'DIGAVAL GARVE, SL',   'address'      =>  'CR UBRIQUE-BENAOCAZ KM2',   'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '607982040',   'codigo'      =>  '4300030100075',  'email'      =>  'DIGAVALGARVE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72330129',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ECOMATERIALES PEYR, SL',  'address'      =>  'CR MEDINA', 'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000106',  'email'      =>  'ECOMATERIALESPEYR@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '25565824J',  'name'      =>  'EMILIO',   'surname'      =>  'GARCIA QUIROS', 'razon'      =>  'EMILIO GARCIA QUIROS',    'address'      =>  'C/ JOSE MARIA JIMENEZ', 'pc'      =>  '11610',  'city'      =>  'GRAZALEMA',    'province'      =>  'Cádiz',    'phone'      =>  '956138847',   'codigo'      =>  '4300010000107',  'email'      =>  'EMILIOGARCIAQUIROS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75763622N',  'name'      =>  'ENCARNACION',  'surname'      =>  'FLORIDO',   'razon'      =>  'ENCARNACION FLORIDO', 'address'      =>  'C/ CAMINO DEL ALMENDRAL',   'pc'      =>  '11510',  'city'      =>  'PUERTO REAL',  'province'      =>  'Cádiz',    'phone'      =>  '956832366',   'codigo'      =>  '4300030100068',  'email'      =>  'ENCARNACIONFLORIDO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11830254',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ENCOFRADOS SAN JOSE 2005 SL', 'address'      =>  'AVDA DE LA INDEPENDENCIA',  'pc'      =>  '11580',  'city'      =>  'SAN JOSE DEL VALLE',   'province'      =>  'Cádiz',    'phone'      =>  '956166032',   'codigo'      =>  '4300010000217',  'email'      =>  'ENCOFRADOSSANJOSE2005@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91853978',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'EPROAN',  'address'      =>  'C/ EMPRENDEDORES',  'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000137',  'email'      =>  'EPROAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11349743',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ESCAYOLAS ESTRADA, SL',   'address'      =>  'PG PELAGATOS C/ SOLIDARIDAD',   'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '856151540',   'codigo'      =>  '4300030100045',  'email'      =>  'ESCAYOLASESTRADA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41767039',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ESCAYOLAS LEBRIJA',   'address'      =>  'CR SANTA LUCIA KM2',    'pc'      =>  '41740',  'city'      =>  'LEBRIJA',  'province'      =>  'SEVILL',   'phone'      =>  '955973137',   'codigo'      =>  '4300010000115',  'email'      =>  'ESCAYOLASLEBRIJA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '47335097Q',  'name'      =>  'ESTHER',   'surname'      =>  'SANCHEZ GARCIA',    'razon'      =>  'ESTHER SANCHEZ GARCIA',   'address'      =>  'C/ PISUERGA',   'pc'      =>  '41740',  'city'      =>  'LEBRIJA',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4301000000207',  'email'      =>  'ESTHERSANCHEZGARCIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11749694',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ESTR ALBAÑILERIA BORNOS,SLU', 'address'      =>  'AVDA CAUCHI',   'pc'      =>  '11640',  'city'      =>  'BORNOS',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000095',  'email'      =>  'ESTRALBAÑILERIABORNOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91677708',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ESTUCO Y DECORACION MARVE, SL',   'address'      =>  'C/ TRIANA', 'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '648164244',   'codigo'      =>  '4300010000171',  'email'      =>  'ESTUCOYDECORACIONMARVE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72179815',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'EUROMATERIALES 2011, SL', 'address'      =>  'CR DE MEDINA',  'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '956403703',   'codigo'      =>  '4300030100010',  'email'      =>  'EUROMATERIALES2011@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11705506',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'EXCV Y TRANS CAMPOS Y ROMERO, SL',    'address'      =>  'CALLE CARRIL DE ONORIO',    'pc'      =>  '11659',  'city'      =>  'PUERTO SERRANO',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4301000000190',  'email'      =>  'EXCVYTRANSCAMPOSYROMERO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A11087285',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'FELIPE CASTELLANO CONSTRUCCIONES',    'address'      =>  'AVD VALDECARRETAS', 'pc'      =>  '11520',  'city'      =>  'ROTA', 'province'      =>  'Cádiz',    'phone'      =>  '956811081',   'codigo'      =>  '4300010000157',  'email'      =>  'FELIPECASTELLANOCONSTRUCCIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31843266L',  'name'      =>  'FERNANDO ',    'surname'      =>  'ARTOLA JIMENEZ',    'razon'      =>  'FERNANDO ARTOLA JIMENEZ', 'address'      =>  'CR BARBATE-VEJER',  'pc'      =>  '11160',  'city'      =>  'BARBATE',  'province'      =>  'Cádiz',    'phone'      =>  '956431358',   'codigo'      =>  '4300030100007',  'email'      =>  'FERNANDOARTOLAJIMENEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11383171',  'name'      =>  'FERNANDO ',    'surname'      =>  'GALVEZ',    'razon'      =>  'FERNANDO GALVEZ, SLU',    'address'      =>  'CR SANLUCAR-CHIPIONA, KM0.5',   'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '956360750',   'codigo'      =>  '4300030100027',  'email'      =>  'FERNANDOGALVEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '44051878R',  'name'      =>  'FERNANDO ',    'surname'      =>  'MEDINA OLIVERA',    'razon'      =>  'FERNANDO MEDINA OLIVERA', 'address'      =>  'C/ CAMINO DE BORNOS',   'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000168',  'email'      =>  'FERNANDOMEDINAOLIVERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11925922',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'FRANBEA OBRAS Y REFORMAS, SL',    'address'      =>  'C/ LARGA',  'pc'      =>  '11620',  'city'      =>  'JEDULA',   'province'      =>  'Cádiz',    'phone'      =>  '956722123',   'codigo'      =>  '4300010000118',  'email'      =>  'FRANBEAOBRASYREFORMAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31304807J',  'name'      =>  'FRANCISCO',    'surname'      =>  'GARCIA BOLAÑOS',    'razon'      =>  'FRANCISCO GARCIA BOLAÑOS',    'address'      =>  'C/ CALDERON DE LA BARCA',   'pc'      =>  '11520',  'city'      =>  'ROTA', 'province'      =>  'Cádiz',    'phone'      =>  '956840028',   'codigo'      =>  '4300030100040',  'email'      =>  'FRANCISCOGARCIABOLAÑOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31659461F',  'name'      =>  'FRANCISCO JAVIER', 'surname'      =>  'REINA NAVAS',   'razon'      =>  'FRANCISCO JAVIER REINA NAVAS',    'address'      =>  'C/ FUENTEZUELA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000127',  'email'      =>  'FRANCISCOJAVIERREINANAVAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31625867Q',  'name'      =>  'FRANCISCO',    'surname'      =>  'LOZANO CARDENAS',   'razon'      =>  'FRANCISCO LOZANO CARDENAS',   'address'      =>  'AV LEBRIJA',    'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000146',  'email'      =>  'FRANCISCOLOZANOCARDENAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A11626223',  'name'      =>  'FRANCISCO',    'surname'      =>  'MARTIN MARTIN', 'razon'      =>  'FRANCISCO MARTIN MARTIN', 'address'      =>  'CR JEREZ ALGECIRAS KM', 'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000056',  'email'      =>  'FRANCISCOMARTINMARTIN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31389986L',  'name'      =>  'FRANCISCO',    'surname'      =>  'PAEZ RUEDA',    'razon'      =>  'FRANCISCO PAEZ RUEDA',    'address'      =>  'CAÑADA DE LOS BARRANCOS, TOCIN',    'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '630716304',   'codigo'      =>  '4300030000173',  'email'      =>  'FRANCISCOPAEZRUEDA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '34063690D',  'name'      =>  'FRANCISCO',    'surname'      =>  'SANCHEZ RAMIREZ',   'razon'      =>  'FRANCISCO SANCHEZ RAMIREZ',   'address'      =>  'C/HUERTA MORALES',  'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000159',  'email'      =>  'FRANCISCOSANCHEZRAMIREZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72179351',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GADESUR BAHIA DE Cádiz, SL',  'address'      =>  'C/ JOSE GARCIA ANGULO', 'pc'      =>  '11001',  'city'      =>  'Cádiz',    'province'      =>  'Cádiz',    'phone'      =>  '956533978',   'codigo'      =>  '4300030100051',  'email'      =>  'GADESURBAHIADECádiz@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B98192123',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GARANTIA DE SATISFACCION, SL/',   'address'      =>  'C/ARQUITECTURA TORNEO', 'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '955813085',   'codigo'      =>  '4300010000097',  'email'      =>  'GARANTIADESATISFACCION@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B93147957',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GESTION 360 EDIFICACION', 'address'      =>  'PLAZA DE FELIZ SAENZ',  'pc'      =>  '29005',  'city'      =>  'Málaga',   'province'      =>  'Málaga',   'phone'      =>  '675920347',   'codigo'      =>  '4300010000208',  'email'      =>  'GESTION360EDIFICACION@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B74183005',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GORDON IMAGEN SL',    'address'      =>  'MERTINEZ MARINA',   'pc'      =>  '33001',  'city'      =>  'OVIEDO',   'province'      =>  'ASTURIAS', 'phone'      =>  '985272672',   'codigo'      =>  '4300010000084',  'email'      =>  'GORDONIMAGEN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72334782',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GORSA BAHIA SL',  'address'      =>  'C JEREZ',   'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000218',  'email'      =>  'GORSABAHIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72350366',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GRUPO NARCISO JURADO E HIJOS 2018, SL',   'address'      =>  'CR DE ROTA KM1',    'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '956371672',   'codigo'      =>  '4300030000165',  'email'      =>  'GRUPONARCISOJURADOEHIJOS2018@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11587813',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'GUADANARES, SL',  'address'      =>  'AVD DE Sevilla',    'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '625440568',   'codigo'      =>  '4300030100019',  'email'      =>  'GUADANARES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11741535',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HERBELGAR, SL',   'address'      =>  'C/ LEMA',   'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000150',  'email'      =>  'HERBELGAR@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11692753',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HEREDEROS GARCIA REGUERA, SL',    'address'      =>  'C/ HORTALES APT 73',    'pc'      =>  '11660',  'city'      =>  'PRADO DEL REY',    'province'      =>  'Cádiz',    'phone'      =>  '956723129',   'codigo'      =>  '4300010000057',  'email'      =>  'HEREDEROSGARCIAREGUERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72201254',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HERMANOS GARCIA PAVON, SL',   'address'      =>  'C/ SAN ONOFRE', 'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '666553141',   'codigo'      =>  '4300030100031',  'email'      =>  'HERMANOSGARCIAPAVON@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'F41699935',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HERMANOS MORON, SCA', 'address'      =>  'C/MIGUEL HERNANDEZ',    'pc'      =>  '41730',  'city'      =>  'LAS CABEZAS DE SAN JUAN',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000040',  'email'      =>  'HERMANOSMORON@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11707320',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HERMANOS SABORIDO VAZQUEZ SL',    'address'      =>  'CR ARCOS PANT GUADALCACIN,KM1', 'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956700080',   'codigo'      =>  '4300030100002',  'email'      =>  'mcsaboridovazquez@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11754827',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HIERROS Y ALUMINIO LA UNION SL',  'address'      =>  'SANTA CRISTINA',    'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956157212',   'codigo'      =>  '4300030000178',  'email'      =>  'HIERROSYALUMINIOLAUNION@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11706405',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HIPERCINE, SL',   'address'      =>  'C/SALINERA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '956730511',   'codigo'      =>  '4300010000011',  'email'      =>  'HIPERCINE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11934106',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HNOS CHACON Y SOBRINO , SL',  'address'      =>  'C/ VENUS',  'pc'      =>  '11580',  'city'      =>  'SAN JOSE DEL VALLE',   'province'      =>  'Cádiz',    'phone'      =>  '956160498',   'codigo'      =>  '4300010000076',  'email'      =>  'HNOSCHACONYSOBRINO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'J11489283',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HNOS VIRUEZ OLIVA,SC',    'address'      =>  'C/ Sevilla',    'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000131',  'email'      =>  'HNOSVIRUEZOLIVA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11752672',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'HORMIGONES LOZAC OBR Y SER, SL',  'address'      =>  'C/ PARADORES PG EL BARRIA', 'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '653985603',   'codigo'      =>  '4300030100060',  'email'      =>  'HORMIGONESLOZACOBRYSER@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A21102157',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'INGENIERIA DE SUELOS Y EXPLOT DE RECURSOS SA',    'address'      =>  'LUIS MONTOTO',  'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '954571914',   'codigo'      =>  '4300030000181',  'email'      =>  'INGENIERIADESUELOSYEXPLOTDERECURSOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11564812',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'INMO SALCO INVERSIONES, SL',  'address'      =>  'PL IND OLIVAR PARC5',   'pc'      =>  '11160',  'city'      =>  'BARBATE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000104',  'email'      =>  'INMOSALCOINVERSIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11416856',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'INMOBISUR SL',    'address'      =>  'CL PEREZ GALDOS',   'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4303000000057',  'email'      =>  'INMOBISUR@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11836103',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'INVERSIONES BORNOS, SL',  'address'      =>  'AV SAN JERONIMO',   'pc'      =>  '11640',  'city'      =>  'BORNOS',   'province'      =>  'Cádiz',    'phone'      =>  '956728241',   'codigo'      =>  '4300010000098',  'email'      =>  'INVERSIONESBORNOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B67294587',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'IXEL APLICACIONES',   'address'      =>  'MANUEL DE SOTO Y MOLINA',   'pc'      =>  '11570',  'city'      =>  'LA BARCA DE LA FLORIDA',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000055',  'email'      =>  'lobostone@icloud.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11241585',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'J MAINE COTO, SL',    'address'      =>  'C/ SOLDADORES PG FADRICA',  'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '956886183',   'codigo'      =>  '4300030100058',  'email'      =>  'administracion@materialesmaine.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11834728',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'JEDUTEC CUBIERTAS Y TEJAS, SL',   'address'      =>  'C/ ANTONIO LOPEZ BUENO',    'pc'      =>  '11620',  'city'      =>  'JEDULA',   'province'      =>  'Cádiz',    'phone'      =>  '650255443',   'codigo'      =>  '4300010000096',  'email'      =>  'JEDUTECCUBIERTASYTEJAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '44051408Z',  'name'      =>  'JESUS',    'surname'      =>  'MORENO DOMINGUEZ',  'razon'      =>  'JESUS MORENO DOMINGUEZ',  'address'      =>  'GOYA',  'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000105',  'email'      =>  'JESUSMORENODOMINGUEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91952812',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'JOANSASUR VALDERRAMA SL', 'address'      =>  'LAZARO RIVAS',  'pc'      =>  '41318',  'city'      =>  'VILLAVERDE DEL RIO',   'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000221',  'email'      =>  'JOANSASURVALDERRAMA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '47560218J',  'name'      =>  'JONATAN',  'surname'      =>  'CASTILLO GUERRERO', 'razon'      =>  'JONATAN CASTILLO GUERRERO',   'address'      =>  'C/ CALVARIO BAJO',  'pc'      =>  '41730',  'city'      =>  'LAS CABEZAS DE SAN JUAN',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000043',  'email'      =>  'JONATANCASTILLOGUERRERO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31708624L',  'name'      =>  'JORGE',    'surname'      =>  'JIMENEZ RODRIGUEZ', 'razon'      =>  'JORGE JIMENEZ RODRIGUEZ', 'address'      =>  'C/PEDRO ALVAREZ',   'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000138',  'email'      =>  'JORGEJIMENEZRODRIGUEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11563228',  'name'      =>  'JOSE ',    'surname'      =>  'AMAYA QUINTERO',    'razon'      =>  'JOSE AMAYA QUINTERO, SL', 'address'      =>  'CRT EL PRADILLO KM 1',  'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '956442900',   'codigo'      =>  '4300030100005',  'email'      =>  'amaya@amayaquintero.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31233368N',  'name'      =>  'JOSE ANTONIO', 'surname'      =>  'GARCIA MORENO', 'razon'      =>  'JOSE ANTONIO GARCIA MORENO',  'address'      =>  'C/ NTRA SÑR DE LA PAZ', 'pc'      =>  '11170',  'city'      =>  'MEDINA SIDONIA',   'province'      =>  'Cádiz',    'phone'      =>  '637839286',   'codigo'      =>  '4300030100067',  'email'      =>  'JOSEANTONIOGARCIAMORENO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75820098T',  'name'      =>  'JOSE', 'surname'      =>  'BARBA GALLARDO',    'razon'      =>  'JOSE BARBA GALLARDO', 'address'      =>  'BD JADRAMIL',   'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000009',  'email'      =>  'JOSEBARBAGALLARDO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31318856D',  'name'      =>  'JOSEFA',   'surname'      =>  'HERRERA BENITEZ',   'razon'      =>  'JOSE FA HERRERA BENITEZ', 'address'      =>  'CR CHIPIONA ROTA KM',   'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030100069',  'email'      =>  'JOSEFAHERRERABENITEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31705187D',  'name'      =>  'JOSE MARIA',   'surname'      =>  'MARQUEZ ORTEGA',    'razon'      =>  'JOSE MARIA MARQUEZ ORTEGA',   'address'      =>  'ALMANZARA', 'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000052',  'email'      =>  'cubiertasmarquez@hotmail,com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75766582M',  'name'      =>  'JOSE MARIA',   'surname'      =>  'TORRES GONZALEZ',   'razon'      =>  'JOSE MARIA TORRES GONZALEZ',  'address'      =>  'C/ LUNA',   'pc'      =>  '11178',  'city'      =>  'PATERNA DE RIVERA',    'province'      =>  'Cádiz',    'phone'      =>  '666016362',   'codigo'      =>  '4300030000170',  'email'      =>  'JOSEMARIATORRESGONZALEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31601760J',  'name'      =>  'JOSE', 'surname'      =>  'NOGUERA SANCHEZ',   'razon'      =>  'JOSE NOGUERA SANCHEZ',    'address'      =>  'TREBUJENA', 'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000020',  'email'      =>  'JOSENOGUERASANCHEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31710747A',  'name'      =>  'JOSE VICENCTE',    'surname'      =>  'GIL HOLGADO',   'razon'      =>  'JOSE VICENTE GIL HOLGADO',    'address'      =>  'CL AZAHAR BQ 1',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000120',  'email'      =>  'JOSEVICENTEGILHOLGADO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '52591940Z',  'name'      =>  'JUAN ',    'surname'      =>  'GALLARDO DONCEL-MORIANO',   'razon'      =>  'JUAN GALLARDO DONCEL-MORIANO',    'address'      =>  'AVDA REY JUAN CARLOS I',    'pc'      =>  '11150',  'city'      =>  'VEJER DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4301000000206',  'email'      =>  'JUANGALLARDODONCEL-MORIANO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '52320681M',  'name'      =>  'JUAN ',    'surname'      =>  'GONZALO LORENZO ALES',  'razon'      =>  'JUAN GONZALO LORENZO ALES',   'address'      =>  'CL POZO REY',   'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '956372005-',  'codigo'      =>  '4300030000066',  'email'      =>  'JUANGONZALOLORENZOALES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75765364Y',  'name'      =>  'JUAN MANUEL',  'surname'      =>  'BERMUDEZ CALDERON', 'razon'      =>  'JUAN MANUEL BERMUDEZ CALDERON',   'address'      =>  'CR DEL MUELLE', 'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000102',  'email'      =>  'JUANMANUELBERMUDEZCALDERON@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '74937673Q',  'name'      =>  'JUAN MANUEL',  'surname'      =>  'PIÑA ASTETE',   'razon'      =>  'JUAN MANUEL PIÑA ASTETE', 'address'      =>  'C/ AMAPOLA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '655601267',   'codigo'      =>  '4300010000179',  'email'      =>  'JUANMANUELPIÑAASTETE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31716844M',  'name'      =>  'JUAN MANUEL',  'surname'      =>  'ROMERO MORATO', 'razon'      =>  'JUAN MANUEL ROMERO MORATO',   'address'      =>  'PINTOR PICASSO',    'pc'      =>  '11659',  'city'      =>  'PUERTO SERRANO',   'province'      =>  'Cádiz',    'phone'      =>  '656978003',   'codigo'      =>  '4300010000091',  'email'      =>  'JUANMANUELROMEROMORATO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '76083415J',  'name'      =>  'JUAN PEDRO',   'surname'      =>  'MATEOS SANCHEZ',    'razon'      =>  'JUAN PEDRO MATEOS SANCHEZ',   'address'      =>  'AV GRULLA NEGRA',   'pc'      =>  '11190',  'city'      =>  'BENALUP-CASAS VIEJAS', 'province'      =>  'Cádiz',    'phone'      =>  '627090212',   'codigo'      =>  '4300030000156',  'email'      =>  'JUANPEDROMATEOSSANCHEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11889870',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'JUCRAEN SL',  'address'      =>  'Sevilla',   'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '6004741383',  'codigo'      =>  '4300010000220',  'email'      =>  'JUCRAEN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A41054784',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LA CANTARERA',    'address'      =>  'C/ DIEGO DE RIAÑO', 'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '609545779',   'codigo'      =>  '4300010000210',  'email'      =>  'LACANTARERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11421914',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LADRILLERA REYES, SL',    'address'      =>  'LG PAGO CHINAREJO, APTDO 39',   'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '650983040',   'codigo'      =>  '4300030100013',  'email'      =>  'LADRILLERAREYES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11799020',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LAS DUNAS MAT DE CONST, SL',  'address'      =>  'C/ ENSENADA',   'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '630051086',   'codigo'      =>  '4300030100025',  'email'      =>  'materialeslasdunas@yahoo.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41634940',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LEONES MAT CONST, SL',    'address'      =>  'C/ FUENTES DE ANDALUCIA',   'pc'      =>  '41620',  'city'      =>  'MARCHENA', 'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300040000012',  'email'      =>  'lozanoramos@telefonica.net', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11699816',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LOZANO RAMOS, SL',    'address'      =>  'PG CIUDAD DEL TRANSP COMUNIC',  'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956157666',   'codigo'      =>  '4300030100044',  'email'      =>  'LOZANORAMOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B04683124',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'LYROLA ING Y OBRAS, SL',  'address'      =>  'C ANTON',   'pc'      =>  '18011',  'city'      =>  'Granada',  'province'      =>  'Granada',  'phone'      =>  '',    'codigo'      =>  '4300010000149',  'email'      =>  'LYROLAINGYOBRAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11709748',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'M B DE OBRAS Y CONST, SLU',   'address'      =>  'AV NTRA SRA LAS MONTAÑAS',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000122',  'email'      =>  'MBDEOBRASYCONST@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '25590482-S', 'name'      =>  'Mª JOSE',  'surname'      =>  'RIOS GONZALEZ', 'razon'      =>  'Mª JOSE RIOS GONZALEZ',   'address'      =>  'C/ LOS ARROYOS',    'pc'      =>  '29350',  'city'      =>  'ARRIATE',  'province'      =>  'Málaga',   'phone'      =>  '',    'codigo'      =>  '4300010000165',  'email'      =>  'MªJOSERIOSGONZALEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91782524',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MACOSUR MAT DE CONST, SL',    'address'      =>  'CAMINO EL GAMO',    'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000182',  'email'      =>  'MACOSURMATDECONST@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41856592',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MADERAS IRIPO,SL',    'address'      =>  'C/ MURILLO',    'pc'      =>  '41780',  'city'      =>  'CORIPE',   'province'      =>  'Cádiz',    'phone'      =>  '955858082',   'codigo'      =>  '4300010000086',  'email'      =>  'MADERASIRIPO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11830858',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MANCOFRA GESTION, SL',    'address'      =>  'AV PRINCIPE DE ESPAÑA', 'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '665095716',   'codigo'      =>  '4300010000117',  'email'      =>  'MANCOFRAGESTION@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31210074V',  'name'      =>  'MANUEL',   'surname'      =>  'BERNAL BENITEZ',    'razon'      =>  'MANUEL BERNAL BENITEZ',   'address'      =>  'C/ AS DE GUI',  'pc'      =>  '11160',  'city'      =>  'BARBATE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000105',  'email'      =>  'MANUELBERNALBENITEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31704007W',  'name'      =>  'MANUEL',   'surname'      =>  'TEJERO CABALLERO',  'razon'      =>  'MANUEL TEJERO CABALLERO', 'address'      =>  'VENENCIADOR',   'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000018',  'email'      =>  'MANUELTEJEROCABALLERO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11011707',  'name'      =>  'MANUEL',   'surname'      =>  'TOLEDO COCA',   'razon'      =>  'MANUEL TOLEDO COCA, SL',  'address'      =>  'C/ MARCOS', 'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '956881505',   'codigo'      =>  '4300030100036',  'email'      =>  'toledococamateriales@infonegocio.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11298171',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MANUEL Y VACA, SL',   'address'      =>  'C/ HIPOLITO SANCHO',    'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '956480660',   'codigo'      =>  '4300030100030',  'email'      =>  'manuelyvaca@telefonica.net', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31333137-F', 'name'      =>  'MANUELA',  'surname'      =>  'MACARRO CARO',  'razon'      =>  'MANUELA MACARRO CARO',    'address'      =>  'CTR PTO -SANLUCAR', 'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000161',  'email'      =>  'MANUELAMACARROCARO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '25590703Y',  'name'      =>  'MARIO',    'surname'      =>  'VIRUEZ DUARTE', 'razon'      =>  'MARIO VIRUEZ DUARTE', 'address'      =>  'AVD HERRERA ORIA',  'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000170',  'email'      =>  'MARIOVIRUEZDUARTE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90366840',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MARPASAN SERVICIOS DIVERSOS SL',  'address'      =>  'C/ TREBUJENA',  'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4301000000204',  'email'      =>  'MARPASANSERVICIOSDIVERSOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41649377',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT CONST J PEREZ E HIJOS, SL',   'address'      =>  'C/ ABUTARDA',   'pc'      =>  '41740',  'city'      =>  'LEBRIJA',  'province'      =>  'Sevilla',  'phone'      =>  '955975249',   'codigo'      =>  '4300010000099',  'email'      =>  'MATCONSTJPEREZEHIJOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11348919',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT CONST LU REYES, SL',  'address'      =>  'C/ ALCALA', 'pc'      =>  '11170',  'city'      =>  'MEDINA SIDONIA',   'province'      =>  'Cádiz',    'phone'      =>  '956412242',   'codigo'      =>  '4300030100012',  'email'      =>  'info@lureyes.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11456092',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT CONST PEDRO BERMUDEZ, SL',    'address'      =>  'C/ REYES CATOLICOS',    'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '670857285',   'codigo'      =>  '4300030100006',  'email'      =>  'MATCONSTPEDROBERMUDEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11929981',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT CONST PEPE EL VITO, SL',  'address'      =>  'PG ID EL BARRIAL C/ EL YUSTO',  'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030100049',  'email'      =>  'MATCONSTPEPEELVITO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72352818',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT DE CONST GARCIA ALVORES SL',  'address'      =>  'AVDA VALENCIA-FINCA EL CARACOL',    'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000166',  'email'      =>  'MATDECONSTGARCIAALVORES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41886441',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MAT DE CONT MONTELLANO, SL',  'address'      =>  'C/ VILLAMARTIN',    'pc'      =>  '41770',  'city'      =>  'MONTELLANO',   'province'      =>  'Sevilla',  'phone'      =>  '954875890',   'codigo'      =>  '4300010000090',  'email'      =>  'MATDECONTMONTELLANO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72069180',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATERIALES BRENES, SL',   'address'      =>  'CR MARQUESADO, KM 1',   'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '956404018',   'codigo'      =>  '4300030100008',  'email'      =>  'materialesbrenes@hotmail.es', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72328537',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATERIALES CARONA',   'address'      =>  'CR CIRCUNVALACION, S/N',    'pc'      =>  '11510',  'city'      =>  'PUERTO REAL',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030100106',  'email'      =>  'MATERIALESMARONA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91453555',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATERIALES CONSTRUCCION VALDEZORRAS, SL', 'address'      =>  'CARRETERA BRENES KM',   'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4301000000202',  'email'      =>  'MATERIALESCONSTRUCCIONVALDEZORRAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72326127',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATERIALES LAS LAGUNAS RA, SL',   'address'      =>  'CR LAS LAGUNAS',    'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '956-534837',  'codigo'      =>  '4300030000038',  'email'      =>  'MATERIALESLASLAGUNAS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41068883',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATERIALES RONDON, SL',   'address'      =>  'CR EL PEDROSO KM 1',    'pc'      =>  '41320',  'city'      =>  'CANTILLANA',   'province'      =>  'Sevilla',  'phone'      =>  '955731725',   'codigo'      =>  '4300010000080',  'email'      =>  'MATERIALESRONDON@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11931011',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MATRERA GESTION XXI, SLU',    'address'      =>  'C/ VIRGEN DE LOS REYES',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '615062790',   'codigo'      =>  '4300010000103',  'email'      =>  'MATRERAGESTIONXXI@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '79251575S',  'name'      =>  'MIGUEL ANGEL', 'surname'      =>  'GONZALEZ BARRIOS',  'razon'      =>  'MIGUEL ANGEL GONZALEZ BARRIOS',   'address'      =>  'C/RIO GUADALETE',   'pc'      =>  '11640',  'city'      =>  'BORNOS',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000077',  'email'      =>  'MIGUELANGELGONZALEZBARRIOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '52928635T',  'name'      =>  'MIGUEL ',  'surname'      =>  'OLMEDO FUENTES',    'razon'      =>  'MIGUEL OLMEDO FUENTES',   'address'      =>  'BD EL COLORADO',    'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '956445755',   'codigo'      =>  '4300030100004',  'email'      =>  'MIGUELOLMEDOFUENTES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72232101',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MILLAN SERV. MONTAJES INT, SL',   'address'      =>  'AD ALGECIRAS',  'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '956401116',   'codigo'      =>  '4300030100076',  'email'      =>  'MILLANSERV.MONTAJESINT@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '23784290J',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'MULTISERVICIOS ALJARILLA',    'address'      =>  'C/ ISLAS BALEARES', 'pc'      =>  '18600',  'city'      =>  'MOTRIL',   'province'      =>  'Granada',  'phone'      =>  '',    'codigo'      =>  '4300010000167',  'email'      =>  'MULTISERVICIOSALJARILLA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11350626',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'NABACONS,SLU',    'address'      =>  'C/RONDA',   'pc'      =>  '11659',  'city'      =>  'PUERTO SERRANO',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000139',  'email'      =>  'NABACONS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '52316022S',  'name'      =>  'NARCISO',  'surname'      =>  'JURADO CAYUSO', 'razon'      =>  'NARCISO JURADO CAYUSO',   'address'      =>  'CR DE ROTA KM 1',   'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '956371672',   'codigo'      =>  '4300030100074',  'email'      =>  'NARCISOJURADOCAYUSO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31575432C',  'name'      =>  'NATIVIDAD',    'surname'      =>  'CABALLERO GARCIA',  'razon'      =>  'NATIVIDAD CABALLERO GARCIA',  'address'      =>  'C/ PLATEROS',   'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '956165000',   'codigo'      =>  '4300030100018',  'email'      =>  'NATIVIDADCABALLEROGARCIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11892445',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'NEOCON BORNOS 2011, SLU', 'address'      =>  'C/ MOLINO ANCHO',   'pc'      =>  '11640',  'city'      =>  'BORNOS',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000102',  'email'      =>  'NEOCONBORNOS2011@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11572195',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'NUPREN, SL',  'address'      =>  'AVD ALAMEDA DEL CURA',  'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '615463200',   'codigo'      =>  '4300010000180',  'email'      =>  'NUPREN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11939444',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'OBRA CUNE',   'address'      =>  'C PARROCO M JIMENEZ SUTIL', 'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000151',  'email'      =>  'OBRACUNE@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11704459',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'OBRAS 89 SL', 'address'      =>  'EXTRAMUROS',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '654536761',   'codigo'      =>  '4300010000215',  'email'      =>  'OBRAS89@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11856903',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'OBRAS Y EXCAVACIONES MANZANO, SL',    'address'      =>  'ARCOS- GUADALCACIN',    'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956726294',   'codigo'      =>  '4300010000140',  'email'      =>  'OBRASYEXCAVACIONESMANZANO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72320476',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'OBRAS Y REFORMAS JCR 2017 SL',    'address'      =>  'C/ ANDRES DE CARMELO AZNAR',    'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '609978363',   'codigo'      =>  '4301000000191',  'email'      =>  'OBRASYREFORMASJCR2017@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91403212',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'OCCIDENTAL PROMOINVEST SL',   'address'      =>  'AVDA LUIS DE MORALES',  'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000219',  'email'      =>  'OCCIDENTALPROMOINVEST@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72132442',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ORTIZ PROYECTOS & INVERSIONES, SL',   'address'      =>  'ADV DIPUTACION',    'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000162',  'email'      =>  'ORTIZPROYECTOS&INVERSIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B91110536',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PARIENTES BALLESTEROS, SL',   'address'      =>  'C/ FRAY MARTIN POVEA',  'pc'      =>  '41650',  'city'      =>  'EL SAUCEJO',   'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000222',  'email'      =>  'PARIENTESBALLESTEROS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31723475N',  'name'      =>  'PASCUAL',  'surname'      =>  'DEL OJO GANFORNINI',    'razon'      =>  'PASCUAL DEL OJO GANFORNINI',  'address'      =>  'C/ TREBUJENA',  'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '691681009',   'codigo'      =>  '4300010000116',  'email'      =>  'PASCUALDELOJOGANFORNINI@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75865592T',  'name'      =>  'PEDRO LUIS',   'surname'      =>  'CASTRO CABRERA',    'razon'      =>  'PEDRO LUIS CASTRO CABRERA',   'address'      =>  'C/ PARROCO SUTIL',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '685548956',   'codigo'      =>  '4300010000123',  'email'      =>  'PEDROLUISCASTROCABRERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'F91617027',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'POLFATIMA, SCA',  'address'      =>  'C/ PRADO',  'pc'      =>  '41750',  'city'      =>  'LOS MOLARES UTRERA',   'province'      =>  'Sevilla',  'phone'      =>  '678418826',   'codigo'      =>  '4300010000089',  'email'      =>  'POLFATIMA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90236787',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'POLVERO GOMEZ, SL',   'address'      =>  'C/ AVEFRIA',    'pc'      =>  '41740',  'city'      =>  'LEBRIJA',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300020000184',  'email'      =>  'POLVEROGOMEZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72354863',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PORRAS HERRERA SL',   'address'      =>  'CTRA DE CHIPIONA A ROTA',   'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000167',  'email'      =>  'PORRASHERRERA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B93006583',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PR VALMALSA SL',  'address'      =>  'VICARIO',   'pc'      =>  '29100',  'city'      =>  'COIN', 'province'      =>  'Málaga',   'phone'      =>  '',    'codigo'      =>  '4300010000104',  'email'      =>  'PRVALMALSA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41855214',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PRISMA 52, SL',   'address'      =>  'C/ JUAN PABLO', 'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000175',  'email'      =>  'PRISMA52@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72063308',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PROMOCIONES MARIO PEREZ, SL', 'address'      =>  'ISAAC PERAL',   'pc'      =>  '11190',  'city'      =>  'BENALUP-CASAS VIEJAS', 'province'      =>  'Cádiz',    'phone'      =>  '956424109',   'codigo'      =>  '4300010000181',  'email'      =>  'PROMOCIONESMARIOPEREZ@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11632023',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PROTOCOVI, SL',   'address'      =>  'C/JILGUERO',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000162',  'email'      =>  'PROTOCOVI@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72169592',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'PYCBEN, SL ', 'address'      =>  'C/ LA TORRE',   'pc'      =>  '11190',  'city'      =>  'BENALUP-CASAS VIEJAS', 'province'      =>  'Cádiz',    'phone'      =>  '607789827',   'codigo'      =>  '4300010000177',  'email'      =>  'PYCBEN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75806777L',  'name'      =>  'RAFAEL',   'surname'      =>  'ARAGON TORRES', 'razon'      =>  'RAFAEL ARAGON TORRES',    'address'      =>  'C/ VIRGEN DEL ROSARIO', 'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '610706345',   'codigo'      =>  '4300030100009',  'email'      =>  'aragontorres22@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '31582151T',  'name'      =>  'RAFAEL',   'surname'      =>  'LINARES PAVON', 'razon'      =>  'RAFAEL LINARES PAVON',    'address'      =>  'AV DE ROTA',    'pc'      =>  '11550',  'city'      =>  'CHIPIONA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030100050',  'email'      =>  'RAFAELLINARESPAVON@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41135690',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'RAJOMA, SL',  'address'      =>  'AV UTRERA', 'pc'      =>  '41720',  'city'      =>  'LOS PALACIOS', 'province'      =>  'Sevilla',  'phone'      =>  '955816132',   'codigo'      =>  '4300010000087',  'email'      =>  'RAJOMA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  '75865351N',  'name'      =>  'RAUL', 'surname'      =>  'GARCIA MARISCAL',   'razon'      =>  'RAUL GARCIA MARISCAL',    'address'      =>  'C/ SAN JOSE',   'pc'      =>  '11639',  'city'      =>  'ALGAR',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000169',  'email'      =>  'RAULGARCIAMARISCAL@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11882479',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'REFORMAS ARCOS MH, SL',   'address'      =>  'C/ ALEJANDRO PEREZ LUGIN',  'pc'      =>  '11630',  'city'      =>  'ARCOS DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '654523843',   'codigo'      =>  '4300010000070',  'email'      =>  'REFORMASARCOSMH@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72268154',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'REYES ARAGON MANTENIMIENTO, SL',  'address'      =>  'CR LAS LAGUNAS',    'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '956534837',   'codigo'      =>  '4300030100038',  'email'      =>  'jesus@reyesaragon.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11928256',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'RIVERA OBRAS EFICIENES SL',   'address'      =>  'AVDA RONDA',    'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4301000000199',  'email'      =>  'RIVERAOBRASEFICIENES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72273923',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'RODRIGUS CATERING GROUP SL',  'address'      =>  'FRANCISCO COSSI OCHOA', 'pc'      =>  '11500',  'city'      =>  'EL PUERTO DE SANTA MARIA', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000060',  'email'      =>  'RODRIGUSCATERINGGROUP@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11700028',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'RUIZ MARTINEZ, SL',   'address'      =>  'AVD DE ANDALUCIA',  'pc'      =>  '11401',  'city'      =>  'JEREZ DE LA FRONTERA', 'province'      =>  'Cádiz',    'phone'      =>  '956144151',   'codigo'      =>  '4300030100026',  'email'      =>  'ruizmartinez@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11620036',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'SAN FRANCISCO MAT DE CONST,SL',   'address'      =>  'PZ SAN FRANCISCO',  'pc'      =>  '11640',  'city'      =>  'BORNOS',   'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000024',  'email'      =>  'SANFRANCISCOMATDECONST@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72296700',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'SARMIENTO 2015 SLU',  'address'      =>  'C/ Cádiz',  'pc'      =>  '11670',  'city'      =>  'EL BOSQUE',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000195',  'email'      =>  'SARMIENTO2015@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41859141',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'SUMINISTROS LOMBARDO,SL', 'address'      =>  'CR TORRE BLANCA KM 0.5',    'pc'      =>  '41500',  'city'      =>  'ALCALA DE GUADAIRA',   'province'      =>  'Sevilla',  'phone'      =>  '667538258',   'codigo'      =>  '4300010000132',  'email'      =>  'suministroslombardo@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72213325',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'SUMINISTROS MILLAN GARCIA, SL',   'address'      =>  'PG ID LA HOYA AV MUSICA NV 2',  'pc'      =>  '11130',  'city'      =>  'CHICLANA DE LA FRONTERA',  'province'      =>  'Cádiz',    'phone'      =>  '856151540',   'codigo'      =>  '4300030100046',  'email'      =>  'SUMINISTROSMILLANGARCIA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11255502',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'SUMINISTROS NOVOSAN, SL', 'address'      =>  'CART PTO STA MARIA KM1',    'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '956362127',   'codigo'      =>  '4300030000159',  'email'      =>  'SUMINISTROSNOVOSAN@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'A21009295',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TEFESA, SA',  'address'      =>  'CR CIRCUNVALACION', 'pc'      =>  '21700',  'city'      =>  'LA PALMA DEL CONDADO', 'province'      =>  'Huelva',   'phone'      =>  '615944132',   'codigo'      =>  '4300030100099',  'email'      =>  'comercial@tefesa.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11226453',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TORRES REVIRIEGO, SL',    'address'      =>  'C/ EL CAZADOR', 'pc'      =>  '11178',  'city'      =>  'PATERNA DE RIVERA',    'province'      =>  'Cádiz',    'phone'      =>  '956416004',   'codigo'      =>  '4300030100020',  'email'      =>  'TORRESREVIRIEGO@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11067691',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TOYBER,SL',   'address'      =>  'SAN MARCOS',    'pc'      =>  '11100',  'city'      =>  'SAN FERNANDO', 'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000176',  'email'      =>  'TOYBER@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11559564',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TRABARCO CONSTRUCCIONES, SL', 'address'      =>  'C/ AZORIN', 'pc'      =>  '11560',  'city'      =>  'TREBUJENA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000154',  'email'      =>  'TRABARCOCONSTRUCCIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B41451022',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TRANSPORTES GREMASA, SL', 'address'      =>  'C/PASI',    'pc'      =>  '41001',  'city'      =>  'Sevilla',  'province'      =>  'Sevilla',  'phone'      =>  '',    'codigo'      =>  '4300010000142',  'email'      =>  'TRANSPORTESGREMASA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B90241613',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'TRANSPORTES Y SERVICIOS VEGA SL', 'address'      =>  'C/ QUINTEROS',  'pc'      =>  '41749',  'city'      =>  'EL CUERVO',    'province'      =>  'Sevilla',  'phone'      =>  '649131507',   'codigo'      =>  '4300010000109',  'email'      =>  'TRANSPORTESYSERVICIOSVEGA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11420858',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'UBRIQUEÑA DE TRANSPORTE 98, SL',  'address'      =>  'BD MIRASIERRA', 'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '956463812',   'codigo'      =>  '4300010000108',  'email'      =>  'UBRIQUEÑADETRANSPORTE98@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11487972',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'V @ D BROTHER ASOCIADOS, SL', 'address'      =>  'AV SOLIS PASCUAL',  'pc'      =>  '11600',  'city'      =>  'UBRIQUE',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300010000147',  'email'      =>  'V@DBROTHERASOCIADOS@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11381472',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'VERDE Y BLANCA, SL',  'address'      =>  'C/ LAGUNA', 'pc'      =>  '11140',  'city'      =>  'CONIL',    'province'      =>  'Cádiz',    'phone'      =>  '687428744',   'codigo'      =>  '4300030100056',  'email'      =>  'VERDEYBLANCA@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B11727450',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'VIPAEURO CONSTRUCCIONES, SL', 'address'      =>  'AVD DE ARCOS',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300020000450',  'email'      =>  'VIPAEUROCONSTRUCCIONES@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'B72323157',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'VIVEROS MAT DE CONST SL', 'address'      =>  'C/ TRONCOSA',   'pc'      =>  '11540',  'city'      =>  'SANLUCAR DE BARRAMEDA',    'province'      =>  'Cádiz',    'phone'      =>  '',    'codigo'      =>  '4300030000160',  'email'      =>  'VIVEROSMATDECONST@gmail.com', 'password' => bcrypt('hiforcem') ]);
User::create([ 'NIF'      =>  'E11915980',  'name'      =>  '', 'surname'      =>  '',  'razon'      =>  'ZAMARRA CB',  'address'      =>  'C/ SAN MATEO',  'pc'      =>  '11650',  'city'      =>  'VILLAMARTIN',  'province'      =>  'Cádiz',    'phone'      =>  '637587322',   'codigo'      =>  '4300010000209',  'email'      =>  'ZAMARRA@gmail.com', 'password' => bcrypt('hiforcem') ]);


        
    }
}
